# Generated by Django 6.1 on 2026-08-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_experience_level_job_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('remoteok', 'RemoteOK'), ('arbeitnow', 'Arbeitnow'), ('adzuna', 'Adzuna')], default='manual', max_length=50),
        ),
    ]
