# Generated by Django 6.1 on 2026-08-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("remoteok", "RemoteOK"),
                    ("arbeitnow", "Arbeitnow"),
                    ("adzuna", "Adzuna"),
                    ("jooble", "Jooble"),
                ],
                default="manual",
                max_length=50,
            ),
        ),
    ]
