# Generated by Django 6.1 on 2026-08-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_automation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildelivery",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
