# Generated by Django 6.1 on 2026-08-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_automation", "0004_gmailoauthstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmailaccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="gmailaccount",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="gmailaccount",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
