# Generated by Django 6.1 on 2026-08-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_cvanalysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("saved", "Saved"),
                    ("to_apply", "To apply"),
                    ("applied", "Applied"),
                    ("reviewed", "Reviewed"),
                    ("assessment", "Assessment"),
                    ("interview", "Interview"),
                    ("offer", "Offer"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("to_status", models.CharField(max_length=20)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="applications.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ("-changed_at",),
            },
        ),
    ]
