# Generated by Django 6.1 on 2026-08-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_applicationnote_applicationreminder_interview_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="cvs/"),
        ),
        migrations.AddField(
            model_name="cv",
            name="file_type",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cv",
            name="parsed_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
