# Generated by Django 6.1 on 2026-08-27 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_cv_file_cv_file_type_cv_parsed_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="parsed_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="CVVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True, default="")),
                ("skills", models.JSONField(blank=True, default=list)),
                ("parsed_text", models.TextField(blank=True, default="")),
                ("parsed_data", models.JSONField(blank=True, default=dict)),
                ("version_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="applications.cv",
                    ),
                ),
            ],
            options={
                "ordering": ("-version_number",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cv", "version_number"), name="unique_cv_version"
                    )
                ],
            },
        ),
    ]
