# Generated by Django 6.1 on 2026-08-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_services", "0003_jobmatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiusage",
            name="error_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="aiusage",
            name="estimated_cost",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="aiusage",
            name="fallback_reason",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="aiusage",
            name="input_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aiusage",
            name="model",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="aiusage",
            name="outcome",
            field=models.CharField(default="success", max_length=20),
        ),
        migrations.AddField(
            model_name="aiusage",
            name="output_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aiusage",
            name="provider",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="aiusage",
            name="total_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
